// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlVeEaObir0YqahzUW1Gx3gpeJuMGutno',
    appId: '1:350708902669:web:61d66b1105474fd3a45e44',
    messagingSenderId: '350708902669',
    projectId: 'chatapp-277ff',
    authDomain: 'chatapp-277ff.firebaseapp.com',
    storageBucket: 'chatapp-277ff.firebasestorage.app',
    measurementId: 'G-3J23ZCN5C3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBt5e5j2UrsxhxEDj-FiMFgwAKxoEzIYVk',
    appId: '1:350708902669:android:4175f5a29eea3481a45e44',
    messagingSenderId: '350708902669',
    projectId: 'chatapp-277ff',
    storageBucket: 'chatapp-277ff.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAlVeEaObir0YqahzUW1Gx3gpeJuMGutno',
    appId: '1:350708902669:web:981b325262fd157da45e44',
    messagingSenderId: '350708902669',
    projectId: 'chatapp-277ff',
    authDomain: 'chatapp-277ff.firebaseapp.com',
    storageBucket: 'chatapp-277ff.firebasestorage.app',
    measurementId: 'G-1PK9DXFD84',
  );
}
